apiVersion: v1
kind: Pod
metadata:
  name: Pod1
  labels:
    name: multischeduler-example
spec:
  schedulerName: default-scheduler
  containers:
  - name: appv2
    image: celery
    resources:
      requests:
        memory: "125Mi"
        cpu: "250m"
      limits:
        memory: "32Mi"
        cpu: "64m"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "32Mi"
        cpu: "64m"
  nodeName: n4
  nodeSelector:
    disktype: ''
  port: 80