apiVersion: v1
kind: Pod
metadata:
  name: pod5
  labels:
    name: multischeduler-example
spec:
  schedulerName: default-scheduler
  containers:
  - name: app2
    image: images.my-company.frontend/app:v4
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "200m"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  nodeName: n3
  nodeSelector:
    disktype: ssd